# Uncomment this line to define a global platform for your project
platform :ios,'8.0'
plugin 'cocoapods-repo-svn', :sources => [
'http://200.200.200.40/svn/repositories/ios/code/trunk/HETSDKs/HETSpecs'
]

source 'https://github.com/CocoaPods/Specs.git'

target '__ProjectName__' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
 
end
